### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by ManuelFernando**

### CODE REVIEW

**Comment by ManuelFernando** [comment]
@parfeon pls review this, we need to add a help section to read.me

**Review by parfeon — DISMISSED** [review]
Looks good.

**Comment by parfeon** [comment]
It was better to make those changes in branch from this merge pull request: https://github.com/pubnub/chat-engine-push-notifications/pull/13

now will have to resolve merge conflicts on README.md (it has been rewritten there).

**Review by parfeon — APPROVED** [review]
I've resolved conflicts here, caused by another merge pull request.
You can merge it.

**Pull request merged**
